### ISSUE TITLE
Death after leveling up exception

### ISSUE THREAD

**Issue by masonturner** [IronicCats/Iteration1#89]
New game>Level up> kill self 

Result: exception

<code>
Exception in thread "Thread-1" java.lang.IllegalArgumentException: Color parameter outside of expected range: Red Green
    at java.awt.Color.testColorValueRange(Color.java:310)
    at java.awt.Color.<init>(Color.java:395)
    at java.awt.Color.<init>(Color.java:369)
    at View.Views.StatusView.render(StatusView.java:51)
    at Controller.States.GameState.render(GameState.java:93)
    at View.View.render(View.java:73)
    at View.View.run(View.java:88)
    at java.lang.Thread.run(Thread.java:745)
</code>

**Comment by Kegley** [comment]
Issue is in Stats class, when player levels up and the player then dies, the health is over 100%

**Comment by broskj** [comment]
Fixed.
